name: sync with official

on:
  schedule:
    - cron:  '15 4 * * *'

jobs:
  update-options:
    runs-on: ubuntu-latest      
    steps:    
        - name: Check out this repository
          run: |
            git clone --branch mirror https://github.com/missdeer/scintilla.git
              
        - name: sync with official
          env:
            GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}        
          run: |
            cd scintilla
            git config user.name "auto-sync-with-official[bot]"
            git config user.email "auto-sync-with-official[bot]@users.noreply.github.com"
            git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
            git branch
            git remote -v
            ls -l
            chmod a+x mirror.mk
            ./mirror.mk
